version: '3.4'
services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
        SA_PASSWORD: "H!lde_1984"
        ACCEPT_EULA: "Y"
  redisdb:
    image: redis:alpine
  love2u.identityprovider:
    image: ${DOCKER_REGISTRY-}love2uidentityprovider
    build:
      context: .
      dockerfile: src/Services/Love2u.IdentityProvider/Dockerfile
    ports:
      - "5100:80"
    depends_on:
      - identitydb
      - redisdb