version: '3.4'

services:
  love2u.angular:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44350
    ports:
      - "5100:80"
      - "44350:443"
  love2u.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44351
      - ASPNETCORE_HOST=Docker
      - ANGULAR_SPA_ORIGIN=https://localhost:44350
      - ConnectionStrings__DefaultConnection=${LOVE2U_IDENTITY_SQLDB:-Server=identitydb;Database=Love2u.IdentityProvider;User Id=sa;Password=H!lde_1984}
      - ConnectionStrings__RedisConnection=${LOVE2U_IDENTITY_REDISDB:-redisdb}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5101:80"
      - "44351:443"
  love2u.apigateway.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44352
      - ANGULAR_SPA_ORIGIN=https://localhost:44350
      - IDENTITY_PROVIDER_URL=http://love2u.identityprovider
      - IDENTITY_PROVIDER_EXTERNAL=https://localhost:44351
    ports:
      - "5102:80"
      - "44352:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  love2u.profileapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - IDENTITY_PROVIDER_URL=http://love2u.identityprovider
    ports:
      - "5103:80"
networks:
  default:
    external:
      name: love2u
      

