version: '3.4'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elastic
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
    depends_on:
      - elastic
  love2u_sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
  redisdb:
    image: redis:alpine
  love2u_mongo:
    image: mongo:latest
    restart: always
  love2u.angular:
    image: ${DOCKER_REGISTRY-}love2uweb
    build:
      context: .
      dockerfile: src/web/Love2u.Angular/Dockerfile
    depends_on:
      - love2u.identityprovider
  love2u.identityprovider:
    image: ${DOCKER_REGISTRY-}love2uidentityprovider
    build:
      context: .
      dockerfile: src/Services/Identity/Love2u.IdentityProvider/Dockerfile    
    depends_on:
      - love2u_sql
      - redisdb
  love2u.apigateway.web:
    image: ${DOCKER_REGISTRY-}love2uapigatewayweb
    build:
      context: .
      dockerfile: src/Gateways/Love2u.APIGateway.Web/Dockerfile
  love2u.profiles.api:
    image: ${DOCKER_REGISTRY-}love2uprofilesapi
    build:
      context: .
      dockerfile: src/Services/Profile/Love2u.Profiles.API/Dockerfile
    depends_on:
      - love2u_mongo
volumes:
  elastic-data:
    driver: local