version: '3.4'
services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "H!lde_1984"
        ACCEPT_EULA: "Y"
  redisdb:
    image: redis:alpine
  love2u.identityprovider:
    image: ${DOCKER_REGISTRY-}love2uidentityprovider
    build:
      context: .
      dockerfile: src/Services/Love2u.IdentityProvider/Dockerfile    
    depends_on:
      - identitydb
      - redisdb
  love2u.angular:
    image: ${DOCKER_REGISTRY-}love2uweb
    build:
      context: .
      dockerfile: src/web/Love2u.Angular/Dockerfile
    depends_on:
      - love2u.identityprovider