version: '3.4'

services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
  elastic:
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      mode: replicated
      replicas: 1
  love2u_sql:
    environment:
        SA_PASSWORD: "H!lde_1984"
        ACCEPT_EULA: "Y"
  love2u.angular:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44350
    ports:
      - "5100:80"
      - "44350:443"
  love2u.identityprovider:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44351
      - ASPNETCORE_HOST=Docker
      - ANGULAR_SPA_ORIGIN=https://localhost:44350
      - ConnectionStrings__DefaultConnection=${LOVE2U_IDENTITY_SQLDB:-Server=love2u_sql;Database=Love2u.IdentityProvider;User Id=sa;Password=H!lde_1984}
      - ConnectionStrings__RedisConnection=${LOVE2U_IDENTITY_REDISDB:-redisdb}
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "5101:80"
      - "44351:443"
  love2u.apigateway.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44352
      - ANGULAR_SPA_ORIGIN=https://localhost:44350
      - IDENTITY_PROVIDER_URL=http://love2u.identityprovider
      - IDENTITY_PROVIDER_EXTERNAL=https://localhost:44351
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - "5102:80"
      - "44352:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  love2u.profiles.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - IDENTITY_PROVIDER_URL=http://love2u.identityprovider
      - ELASTICSEARCH_HOSTS=http://elastic:9200
      - CosmosDB__Uri=https://l2u-tst-cosmos-db.documents.azure.com:443/
      - CosmosDB__Key=Q5IzeWPlA9e3tLz4aoyBcfPF6gq6BuK6dG4mhIKMZVJaQ5lCofVKp9OhtAjLb40H2qHeopSTezjc3QOkgO3s0A==
    ports:
      - "5103:80"
      - "44353:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
networks:
  default:
    external:
      name: love2u